### ISSUE TITLE
Use filter_id parameter instead of providing default API key

### ISSUE THREAD

**Issue by liamwhite** [Bitz/Derpibooru-Downloader#1]
Please use the `filter_id` parameter as listed on the API docs page, like so
```
GET /search.json?filter_id=56027&q=*
```
Do not embed user API keys in public repositories. I will reset the associated account's key once you have removed the it from the repository.

**Comment by Bitz** [comment]
Huh, I could have sworn I used the API Key on the API page.
You can go ahead and reset it- thanks.

 As for the filter, is it really necessary? I would essentially end up using the default everything filter, which seems to end up being used defaultly. 

In hindsight, even an API Key is unnecessary.

**Comment by joeyponi** [comment]
The site does not have a default/public API key. That page is dynamic and lists your own personal API key instead. I checked the key you reference in the source code, and it is tied to your "DerpBot" account.

(Note that @liamwhite and myself are both coders for Derpibooru)

**Comment by joeyponi** [comment]
Using an API key would be useful for users wanting to run the script under their own filter, so I would recommend leaving that option. But an API key is not a mandatory option either, the site will just fall back to the default filter if no key is presented.

**Comment by Bitz** [comment]
Heya, nice to meet ya guys. 
Yeah, its the API key I was using from my other account that I used for my other project.

And I will make both filters and api keys and filters ids optional.
